spring:
  application:
    name: library
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
#    comando para mudar as cores dos logs no console!!!
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){blue} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        marrafon91: trace
    org:
      springframework:
        web: debug
        security: trace

#Os 5 nives de logging
# trace, debug, info, warn, error

management:
  server:
    port: 9090 #ideal colocar uma porta separada para o ACTUATOR!!!
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  override-with-generic-response: false